### ISSUE TITLE
doesn't export types

### ISSUE THREAD

**Issue by jacoobes** [shrimplejs/locales#1]
Package doesn't export types (properly), so it cant work in typescript
https://www.npmjs.com/package/shrimple-locales?activeTab=code
View the index.d.ts, index.d.mts

**Comment by SrIzan10** [comment]
wha

**Comment by SrIzan10** [comment]
more professionally speaking:tm:, my tsup config isn’t working correctly so i’ll see later tomorrow

**Comment by SrIzan10** [comment]
https://github.com/SrIzan10/shrimple-locales/releases/tag/v0.1.2
